// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sima_Web.Models
{
    public class CustomerConfiguration : IEntityTypeConfiguration<Customer>
    {
        public void Configure(EntityTypeBuilder<Customer> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Customer_pk")
                .IsClustered(false);

            entity.ToTable("Customer");

            entity.HasIndex(e => e.Id)
                .HasName("Customer_Id_uindex")
                .IsUnique();

            entity.Property(e => e.AddressStreet).IsRequired();

            entity.Property(e => e.FirstName).IsRequired();

            entity.Property(e => e.LastName).IsRequired();

            entity.Property(e => e.MiddleName).IsRequired();
        }
    }
}
