// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sima_Web.Models
{
    public class QuarterConfiguration : IEntityTypeConfiguration<Quarter>
    {
        public void Configure(EntityTypeBuilder<Quarter> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("Quarters_pk")
                .IsClustered(false);

            entity.HasIndex(e => e.Id)
                .HasName("Quarters_Id_uindex")
                .IsUnique();

            entity.Property(e => e.AddressStreet).IsRequired();

            entity.Property(e => e.Size).IsRequired();

            entity.HasOne(d => d.AddressArea)
                .WithMany(p => p.Quarters)
                .HasForeignKey(d => d.AddressAreaId)
                .HasConstraintName("Quarters_Area_Id_fk");

            entity.HasOne(d => d.Owner)
                .WithMany(p => p.Quarters)
                .HasForeignKey(d => d.OwnerId)
                .HasConstraintName("Quarters_Customer_Id_fk");

            entity.HasOne(d => d.TypeHouse)
                .WithMany(p => p.Quarters)
                .HasForeignKey(d => d.TypeHouseId)
                .HasConstraintName("Quarters_TypeHouse_Id_fk");
        }
    }
}
