// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Sima_Web.Models
{
    public class TypeHouseConfiguration : IEntityTypeConfiguration<TypeHouse>
    {
        public void Configure(EntityTypeBuilder<TypeHouse> entity)
        {
            entity.HasKey(e => e.Id)
                .HasName("TypeHouse_pk")
                .IsClustered(false);

            entity.ToTable("TypeHouse");

            entity.HasIndex(e => e.Id)
                .HasName("TypeHouse_Id_uindex")
                .IsUnique();

            entity.Property(e => e.Name).IsRequired();
        }
    }
}
