// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


using Sima_Web.Properties;


namespace Sima_Web.Models
{
    public partial class Area
    {
        public Area()
        {
            Quarters = new HashSet<Quarter>();
        }

        public int Id { get; set; }
        [Display(ResourceType = typeof(Resources),Name = "Area_Name_AreaName")]
        public string Name { get; set; }

        public virtual ICollection<Quarter> Quarters { get; set; }
    }
}


/*
services.AddMvc()
.AddDataAnnotationsLocalization(options =>
{
options.DataAnnotationLocalizerProvider = (type, factory) =>
factory.Create(typeof(Resources));
});*/
