// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sima_Web.Models
{
    public partial class Swap
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int CurrentQuartersId { get; set; }
        public int SwapQuartersId { get; set; }
        public DateTime SwapDate { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Quarter SwapQuarters { get; set; }
    }
}
