// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Sima_Web.Models
{
    public partial class TypeHouse
    {
        public TypeHouse()
        {
            Quarters = new HashSet<Quarter>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Quarter> Quarters { get; set; }
    }
}
